/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
}

class FmodSFX {
    public static inline var changebin:String = "event:/SFX/Change/changebin";
    public static inline var changebin1:String = "event:/SFX/Change/changebin1";
    public static inline var changebin2:String = "event:/SFX/Change/changebin2";
    public static inline var changebin3:String = "event:/SFX/Change/changebin3";
    public static inline var changebin4:String = "event:/SFX/Change/changebin4";
    public static inline var changebin5:String = "event:/SFX/Change/changebin5";
    public static inline var changebin6:String = "event:/SFX/Change/changebin6";
    public static inline var changebin7:String = "event:/SFX/Change/changebin7";
    public static inline var delight:String = "event:/SFX/Delight/delight";
    public static inline var delight1:String = "event:/SFX/Delight/delight1";
    public static inline var delight2:String = "event:/SFX/Delight/delight2";
    public static inline var delight3:String = "event:/SFX/Delight/delight3";
    public static inline var delight4:String = "event:/SFX/Delight/delight4";
    public static inline var delight5:String = "event:/SFX/Delight/delight5";
    public static inline var delight6:String = "event:/SFX/Delight/delight6";
    public static inline var ding:String = "event:/SFX/Ding/ding";
    public static inline var ding1:String = "event:/SFX/Ding/ding1";
    public static inline var ding2:String = "event:/SFX/Ding/ding2";
    public static inline var disgust:String = "event:/SFX/Disgust/disgust";
    public static inline var disgust1:String = "event:/SFX/Disgust/disgust1";
    public static inline var disgust2:String = "event:/SFX/Disgust/disgust2";
    public static inline var disgust3:String = "event:/SFX/Disgust/disgust3";
    public static inline var disgust4:String = "event:/SFX/Disgust/disgust4";
    public static inline var disgust5:String = "event:/SFX/Disgust/disgust5";
    public static inline var happy:String = "event:/SFX/Happy/happy";
    public static inline var happy1:String = "event:/SFX/Happy/happy1";
    public static inline var happy2:String = "event:/SFX/Happy/happy2";
    public static inline var happy3:String = "event:/SFX/Happy/happy3";
    public static inline var happy4:String = "event:/SFX/Happy/happy4";
    public static inline var happy5:String = "event:/SFX/Happy/happy5";
    public static inline var happy6:String = "event:/SFX/Happy/happy6";
    public static inline var leverOn:String = "event:/SFX/Lever/leverOn";
    public static inline var mediocre:String = "event:/SFX/Mediocre/mediocre";
    public static inline var mediocre1:String = "event:/SFX/Mediocre/mediocre1";
    public static inline var mediocre2:String = "event:/SFX/Mediocre/mediocre2";
    public static inline var mediocre3:String = "event:/SFX/Mediocre/mediocre3";
    public static inline var mediocre4:String = "event:/SFX/Mediocre/mediocre4";
    public static inline var mediocre5:String = "event:/SFX/Mediocre/mediocre5";
    public static inline var mediocre6:String = "event:/SFX/Mediocre/mediocre6";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var plop:String = "event:/SFX/Plop/plop";
    public static inline var plop1:String = "event:/SFX/Plop/plop1";
    public static inline var plop2:String = "event:/SFX/Plop/plop2";
    public static inline var plop3:String = "event:/SFX/Plop/plop3";
    public static inline var plop4:String = "event:/SFX/Plop/plop4";
    public static inline var release:String = "event:/SFX/Release/release";
    public static inline var release1:String = "event:/SFX/Release/release1";
    public static inline var release10:String = "event:/SFX/Release/release10";
    public static inline var release2:String = "event:/SFX/Release/release2";
    public static inline var release3:String = "event:/SFX/Release/release3";
    public static inline var release4:String = "event:/SFX/Release/release4";
    public static inline var release5:String = "event:/SFX/Release/release5";
    public static inline var release6:String = "event:/SFX/Release/release6";
    public static inline var release7:String = "event:/SFX/Release/release7";
    public static inline var release8:String = "event:/SFX/Release/release8";
    public static inline var release9:String = "event:/SFX/Release/release9";
    public static inline var slap:String = "event:/SFX/Slap/slap";
    public static inline var slap1:String = "event:/SFX/Slap/slap1";
    public static inline var slap2:String = "event:/SFX/Slap/slap2";
    public static inline var slap3:String = "event:/SFX/Slap/slap3";
    public static inline var pour1:String = "event:/SFX/Soda/pour1";
    public static inline var transition:String = "event:/SFX/Transitions/transition";
    public static inline var transition1:String = "event:/SFX/Transitions/transition1";
    public static inline var transition2:String = "event:/SFX/Transitions/transition2";
    public static inline var transition3:String = "event:/SFX/Transitions/transition3";
    public static inline var transition4:String = "event:/SFX/Transitions/transition4";
    public static inline var transition5:String = "event:/SFX/Transitions/transition5";
    public static inline var transition6:String = "event:/SFX/Transitions/transition6";
    public static inline var unhappy:String = "event:/SFX/Unhappy/unhappy";
    public static inline var unhappy1:String = "event:/SFX/Unhappy/unhappy1";
    public static inline var unhappy2:String = "event:/SFX/Unhappy/unhappy2";
    public static inline var unhappy3:String = "event:/SFX/Unhappy/unhappy3";
    public static inline var unhappy4:String = "event:/SFX/Unhappy/unhappy4";
    public static inline var unhappy5:String = "event:/SFX/Unhappy/unhappy5";
    public static inline var unhappy6:String = "event:/SFX/Unhappy/unhappy6";
    public static inline var unhappy7:String = "event:/SFX/Unhappy/unhappy7";
}
