/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
}

class FmodSFX {
    public static inline var changebin1:String = "event:/SFX/Change/changebin1";
    public static inline var changebin2:String = "event:/SFX/Change/changebin2";
    public static inline var changebin3:String = "event:/SFX/Change/changebin3";
    public static inline var changebin4:String = "event:/SFX/Change/changebin4";
    public static inline var changebin5:String = "event:/SFX/Change/changebin5";
    public static inline var changebin6:String = "event:/SFX/Change/changebin6";
    public static inline var changebin7:String = "event:/SFX/Change/changebin7";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
}
